#!/sbin/busybox sh

cd /

mount -t proc proc /proc
mount -t sysfs sys /sys

mkdir -p /dev/block

for i in 0 1 2; do
	block=$((19+$i))
	minor=$((11+$i))
	mknod /dev/block/mmcblk0p$block b 259 $minor
done

mknod /dev/block/loop0 b 7 0

mount -t ext4 /dev/block/mmcblk0p21 /data

out() {
	umount -f /system
	umount -f /data

	chmod 755 /init
	chmod 644 /*.universal5410
	chmod 644 /*.rc
	chmod 644 /*.prop
	chmod -R 755 /lib

	exec /init
}

prepareKnox() {
	BP="/system/build.prop"

	if grep -q ro.config.tima=1 $BP; then
		sed -i "s/ro.config.tima=1/ro.config.tima=0/g" $BP
	fi

	if grep -q ro.build.selinux=1 $bp; then
		sed -i "s/ro.build.selinux=1/ro.build.selinux=0/g" $BP
	fi

	APKS="KNOXAgent.apk KNOXAgent.odex KnoxAttestationAgent.apk KnoxAttestationAgent.odex KNOXStore.apk KNOXStore.odex KNOXStub.apk ContainerAgent.apk ContainerAgent.odex"

	for APK in $APKS; do
		if [ -f /system/app/$APK ]; then
			rm /system/app/$APK
		fi
	done
}

ROM=`cat /data/media/.rom`
[ -e /data/media/.rom ] || ROM=0

if grep -q bootmode=2 /proc/cmdline || [ -e /data/media/rebootrs ]; then
	rm -f /data/media/rebootrs
	mv -f /res/etc /
	mv -f /res/aosp43/* /
	mv -f /res/recovery/* /
	out
fi

mkdir -p /data/media/0/romswitcher-tmp
if [ -e /data/media/0/romswitcher-tmp/manualboot ]; then
    if [ -e /data/media/.nextboot ]; then
		rm -f /data/media/.nextboot
	else
		mv -f /res/etc /
		mv -f /res/aosp43/* /
		mv -f /res/recovery/* /
		mv -f /init.rc.2 /init.rc
		out
	fi
fi

[ -e /data/media/.nextboot ] && rm -f /data/media/.nextboot

[ "$ROM" == "0" ] && mount -t ext4 /dev/block/mmcblk0p20 /system
[ "$ROM" == "1" ] && mount -t ext4 /data/media/.secondrom/system.img /system
[ "$ROM" == "2" ] && mount -t ext4 /data/media/.thirdrom/system.img /system
[ "$ROM" == "3" ] && mount -t ext4 /dev/block/mmcblk0p19 /system

if [ -f /system/framework/twframework.jar ]; then
    mv -f /res/sec43/* /
    prepareKnox
elif grep -q ro.build.version.sdk=19 /system/build.prop ; then
    mv -f /res/aosp44/* /
else
    mv -f /res/aosp43/* /
fi

[ "$ROM" == "0" ] || mv -f /fstab.universal5410.2 /fstab.universal5410
[ "$ROM" == "1" ] && mv -f /init.universal5410.rc.second /init.universal5410.rc
[ "$ROM" == "2" ] && mv -f /init.universal5410.rc.third /init.universal5410.rc
[ "$ROM" == "3" ] && mv -f /init.universal5410.rc.fourth /init.universal5410.rc

out