#!/sbin/busybox sh

cd /sbin

for i in $(./busybox --list)
do
	./busybox ln -s busybox $i
done

cd /

mount -t proc proc /proc
mount -t sysfs sysfs /sys

loadRamdisk () {
	umount -f /system
	mv -f /res/ramdisks/$1/* /

	rm /init
	mv -f /init.0 /init

	exec /init
	exit
}

mkdir /dev
mkdir /dev/block
mknod /dev/block/mmcblk0p20 b 259 12
mount -t ext4 /dev/block/mmcblk0p20 /system

if grep -q 1 /sys/class/power_supply/battery/batt_lp_charging ; then
	loadRamdisk sec422
fi

if [ -f /system/framework/twframework.jar ]; then
	if grep -q ro.build.version.release=4.2.2 /system/build.prop; then
		loadRamdisk sec422
	fi
else
	if grep -q ro.build.version.release=4.3 /system/build.prop; then
		cp -a /lib/modules/* /system/modules/
		loadRamdisk aosp43
	fi
fi


